### ISSUE TITLE
Create a HS Legal Repository

### ISSUE THREAD

**Issue by Web3Master** [hyper-scale/race#80]
Hi,

I wanted to organize Legal into Github, to collaborate on a Wyoming DAO LLC.

I thought it may be best to have a separate Repo rather send a PR to create a folder within the Race or Front End Repos.  

Thoughts?

[Wyoming Secretary of State - DAO FAQ.pdf](https://github.com/hyper-scale/race/files/7720025/Wyoming.Secretary.of.State.-.DAO.FAQ.pdf)
[Wyoming Secretary of State - DAO LLC Instructions and Form Articles of Organization.pdf](https://github.com/hyper-scale/race/files/7720028/Wyoming.Secretary.of.State.-.DAO.LLC.Instructions.and.Form.Articles.of.Organization.pdf)
[Wyoming Statute 17-31-(101-115) - DAO Supplement.pdf](https://github.com/hyper-scale/race/files/7720029/Wyoming.Statute.17-31-.101-115.-.DAO.Supplement.pdf)

**Comment by tomknig** [comment]
I am supportive too. It's great seeing you guys planning to manage these things in GitHub. I'd love to see us managing most of our own documents as `markdown`, `org`, or otherwise open plain text files instead of binary (e.g. `pdf`). That'd be cool for versioning them and tracking changes.

**Comment by kareemarab** [comment]
Yup, I second this too. Like @tomknig said, this will help w/ versioning which is pretty relevant to legal docs.

**Comment by kurdybacha** [comment]
+1 to that!

**Comment by tomknig** [comment]
https://github.com/hyper-scale/legal has been created :slightly_smiling_face: 

I've also drafted an idea how we as a community could manage the GitHub configuration in code. Idea is implemented by using [Terraform](https://www.terraform.io/) with the [GitHub Provider](https://registry.terraform.io/providers/integrations/github/latest/docs). You can find an exemplary implementation here: https://github.com/hyper-scale/github CI is of course not yet wired up, otherwise, it would already interfere with the actual GitHub setup. Creating a new repository `legal` would become a pull request. See the example here: https://github.com/hyper-scale/github/pull/1
This setup would make the GitHub Organization itself contribute-able.

**Comment by JamesGannon-Comp** [comment]
Thanks to Kevalin we have a repo now https://github.com/hyper-scale/legal

**Comment by tomknig** [comment]
everyone happy to close this issue?
